# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import sleep.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_start', models.DateTimeField(verbose_name='state start')),
                ('state', models.PositiveSmallIntegerField(validators=[sleep.models.validate_sleep_state], verbose_name='sleep state')),
            ],
        ),
    ]
